import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}

        <svg
          xmlns="http://www.w3.org/2000/svg"
          style={{ display: "none", visibility: "hidden" }}
          focusable={false}
          aria-hidden={true}>
          <symbol id="down-arrow" viewBox="0 0 48 48">
            <title>Down Arrow Icon</title>
            <desc>Down arrow indicates user interaction toggles.</desc>
            <path d="M14.83 16.42l9.17 9.17 9.17-9.17 2.83 2.83-12 12-12-12z" />
            <path d="M0-.75h48v48h-48z" fill="none" />
          </symbol>
        </svg>
      </body>
    </html>
  );
}
